global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus scraping itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Your Node backend (we'll add /metrics later)
  - job_name: 'server'
    metrics_path: /metrics
    static_configs:
      - targets: ['server:4000']
